# Generated by Django 4.2.11 on 2024-06-12 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRecoverPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('code', models.IntegerField(verbose_name='Codigo de seguridad')),
                ('expiration', models.DateTimeField(verbose_name='tiempo de valido  del codigo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Codigo de seguridad restablecimiento de contraseña',
                'verbose_name_plural': 'Codigos de seguridad restablecimiento de contraseñas',
            },
        ),
    ]
