# Generated by Django 4.2.11 on 2024-07-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_coderecoverpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_id',
            field=models.IntegerField(default=48, unique=True),
        ),
    ]
