# Generated by Django 4.2.11 on 2024-05-28 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Mis usuraios'},
        ),
    ]
