# Generated by Django 4.2.11 on 2024-05-28 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Mis usuraios', 'verbose_name_plural': 'Mis usureaios'},
        ),
    ]
