# Generated by Django 4.2.11 on 2024-05-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_users_userscustom'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscustom',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
