# Generated by Django 4.2.11 on 2024-08-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_number_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_id',
            field=models.IntegerField(unique=True),
        ),
    ]
