# Generated by Django 4.2.11 on 2024-08-24 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_number_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ciudadano', 'Ciudadano'), ('policia', 'Policía'), ('ambulancia', 'Ambulancia'), ('bomberos', 'Bomberos')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AlterModelOptions(
            name='coderecoverpassword',
            options={'verbose_name': 'Código de seguridad restablecimiento de contraseña', 'verbose_name_plural': 'Códigos de seguridad restablecimiento de contraseñas'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RenameField(
            model_name='coderecoverpassword',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='coderecoverpassword',
            name='code',
            field=models.IntegerField(verbose_name='Código de seguridad'),
        ),
        migrations.AlterField(
            model_name='coderecoverpassword',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coderecoverpassword',
            name='expiration',
            field=models.DateTimeField(verbose_name='Tiempo válido del código'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role'),
        ),
    ]
