# Generated by Django 4.2.11 on 2024-08-24 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_role_alter_coderecoverpassword_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_id', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('plate_vehicle', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuario de emergencias',
                'verbose_name_plural': 'usuarios de emergencias',
            },
        ),
    ]
