# Generated by Django 4.2.11 on 2024-08-24 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_emergencyrolemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrolemodel',
            name='requested_role',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencyrolemodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20),
        ),
    ]
