# Generated by Django 4.2.11 on 2024-08-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_emergencyrolemodel_requested_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencyrolemodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='emergencyrolemodel',
            name='adress',
        ),
        migrations.AlterField(
            model_name='emergencyrolemodel',
            name='number_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emergencyrolemodel',
            name='plate_vehicle',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='emergencyrolemodel',
            name='requested_role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emergencyrolemodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
