# Generated by Django 4.2.11 on 2024-08-25 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_emergencyrolemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrolemodel',
            name='requested_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_role_requests', to='users.role'),
        ),
    ]
