# Generated by Django 4.2.11 on 2024-08-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_emergencyrolemodel_requested_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrolemodel',
            name='adress',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
