version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: my-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    command: ["/scripts/command-dev.sh"]
    volumes:
      - .:/src
      - ./scripts:/scripts
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=my-app
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
