# Generated by Django 4.2.11 on 2024-06-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0003_emergency_created_at_emergency_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencytype',
            options={'verbose_name': 'Tipo de Emergencia', 'verbose_name_plural': 'Tipos de Emergencias'},
        ),
        migrations.AlterField(
            model_name='emergencytype',
            name='icon',
            field=models.ImageField(upload_to=''),
        ),
    ]
